### ISSUE TITLE
[Feat] : 프로필 상세 조회 UI 구현

### ISSUE THREAD

**Issue by arinming** [Mnseo/Kusitms_android#63]
### To-do
**ProfileDetail**
- [x] 메인 프로필 컴포넌트 구현
- [x] 상세 프로필 컴포넌트 구현
- [x] 노션 링크 이동 구현
