### ISSUE TITLE
[FEAT] 프로필 API 링크 연결 및 검색, 필터링 추가

### ISSUE THREAD

**Issue by arinming** [Mnseo/Kusitms_android#83]
### To-do
**Profile**
- [x] 잘못된 링크 연결 시 강제종료 되는 현상 해결
- [x] 검색 했을 때 프로필 상세 조회 연결
- [x] 파트 필터링 구현
