### ISSUE TITLE
[FEAT] 홈 화면 UI 구현

### ISSUE THREAD

**Issue by arinming** [Mnseo/Kusitms_android#85]
### To-do
**HomeScreen**
- [x] 프로필 정보 컴포넌트 구현
- [x] 커리큘럼 정보 컴포넌트 구현
- [x] 팀매칭 정보 컴포넌트 구현

### Other Information
<img width="445" alt="image" src="https://github.com/Mnseo/Kusitms_android/assets/97820109/bea23598-1ea8-4b76-88d7-1fc862027875">
