### ISSUE TITLE
[REFACTOR] 프로필 VIEW 피그마 변경 사항 반영

### ISSUE THREAD

**Issue by arinming** [Mnseo/Kusitms_android#96]
### To-do
- [x] 말 줄임 반영
- [x] 파트 선택 -> 전체로 수정
- [x] 다가오는 커리큘럼 없는 경우 화면 반영
- [x] 와이파이 / 비밀번호 정렬 반영

### Other Information
